id: P008225
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W25263
  title: སྙན་ངག་གི་མིག་ཆུ
  author: ''
  volumes:
    b18cacbeb55e4070844633f7c5bce205:
      image_group_id: I5838
      title: ''
      volume_number: 1
      total_pages: 222
      base_file: v001.txt
