id: I444E4154
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:33:49+00:00'
last_modified: '2022-06-08T08:03:30.269035+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25263
  title: སྙན་ངག་གི་མིག་ཆུ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    6BF8:
      image_group_id: I5838
      title: ''
      total_pages: 222
      order: 1
      base_file: 6BF8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
